"""create translation_logs table

Revision ID: 01c9e93aa68c
Revises: 
Create Date: 2026-02-27 17:48:15.543310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision: str = '01c9e93aa68c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('translation_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('phone_hash', sa.String(length=64), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('doc_type', sa.String(length=32), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('drug_count', sa.Integer(), nullable=False),
    sa.Column('has_audio', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_translation_logs_created_at'), 'translation_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_translation_logs_phone_hash'), 'translation_logs', ['phone_hash'], unique=False)
    op.create_index(op.f('ix_translation_logs_request_id'), 'translation_logs', ['request_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_translation_logs_request_id'), table_name='translation_logs')
    op.drop_index(op.f('ix_translation_logs_phone_hash'), table_name='translation_logs')
    op.drop_index(op.f('ix_translation_logs_created_at'), table_name='translation_logs')
    op.drop_table('translation_logs')
    # ### end Alembic commands ###
