"""add confidence_avg to translation_logs

Revision ID: 0d4210616807
Revises: 01c9e93aa68c
Create Date: 2026-02-27 18:09:12.250539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision: str = '0d4210616807'
down_revision: Union[str, None] = '01c9e93aa68c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('translation_logs', sa.Column('confidence_avg', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('translation_logs', 'confidence_avg')
    # ### end Alembic commands ###
